version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ssllaavv/games-archive:latest  # Replace with your Docker Hub username
    restart: always
    command: gunicorn games_archive.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static-files
      - media_volume:/app/media
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web

#  migration:
#    image: ssllaavv/games-archive:latest  # Replace with your Docker Hub username
#    command: bash -c "python manage.py makemigrations && python manage.py migrate"
#    volumes:
#      - static_volume:/app/static-files
#      - media_volume:/app/media
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: