# Generated by Django 5.1.1 on 2024-10-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_to_users_game_to_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='to_users',
            new_name='to_user',
        ),
    ]
