# Generated by Django 5.1.1 on 2024-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0005_console_logo_alter_console_cover_image_and_more'),
        ('games', '0004_rename_to_users_game_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='to_consoles',
            field=models.ManyToManyField(blank=True, to='consoles.console'),
        ),
    ]
