# Generated by Django 5.1.1 on 2024-10-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0002_console_to_user'),
        ('games', '0004_rename_to_users_game_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='to_consoles',
            field=models.ManyToManyField(blank=True, to='consoles.console'),
        ),
    ]
