# Generated by Django 5.1.1 on 2024-11-07 10:44

import django.core.validators
import games_archive.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_options_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/', validators=[games_archive.custom_validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(700)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, validators=[games_archive.custom_validators.validate_release_year]),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, validators=[games_archive.custom_validators.validate_name_is_longer_than_2_characters]),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2500)]),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='picture',
            field=models.ImageField(upload_to='game_screenshots/', validators=[games_archive.custom_validators.validate_file_size]),
        ),
    ]
