# Generated by Django 5.1.1 on 2024-11-07 10:50

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0008_remove_console_unique_console_name_ci_and_more'),
        ('games', '0007_alter_game_cover_image_alter_game_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_game_title_ci', violation_error_message='Game with this title already exists!'),
        ),
    ]
