# Generated by Django 5.1.1 on 2024-11-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
