# Generated by Django 5.1.1 on 2024-10-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_gamerating_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolecomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ['-created_on']},
        ),
    ]
