# Generated by Django 5.1.1 on 2024-10-28 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_consolecomment_options_and_more'),
        ('consoles', '0002_console_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolerating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='consolerating',
            unique_together={('from_user', 'to_console')},
        ),
    ]
