# Generated by Django 5.1.1 on 2024-11-06 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_consolerating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolecomment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(700)]),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(700)]),
        ),
    ]
