# Generated by Django 5.1.1 on 2024-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0004_alter_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='console_covers/'),
        ),
        migrations.AlterField(
            model_name='console',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='console_covers/'),
        ),
        migrations.AlterField(
            model_name='console',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
