# Generated by Django 5.1.1 on 2024-11-06 14:33

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0005_console_logo_alter_console_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={'ordering': ['-pk']},
        ),
        migrations.AddConstraint(
            model_name='console',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_console_name_ci'),
        ),
    ]
