# Generated by Django 5.1.1 on 2024-11-06 15:15

import games_archive.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0006_alter_console_options_console_unique_console_name_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='console_covers/', validators=[games_archive.custom_validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='console',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='console_covers/', validators=[games_archive.custom_validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(max_length=100, validators=[games_archive.custom_validators.validate_name_is_longer_than_2_characters]),
        ),
        migrations.AlterField(
            model_name='console',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, validators=[games_archive.custom_validators.validate_release_year]),
        ),
    ]
