# Generated by Django 5.1.1 on 2024-11-07 10:44

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0007_alter_console_cover_image_alter_console_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='console',
            name='unique_console_name_ci',
        ),
        migrations.AlterField(
            model_name='console',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(700)]),
        ),
        migrations.AddConstraint(
            model_name='console',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_console_name_ci', violation_error_message='Console with this name already exists!'),
        ),
    ]
