# Generated by Django 5.1.1 on 2024-09-21 10:29

import django.core.validators
import games_archive.accounts.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesarchiveuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gamesarchiveuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='gamesarchiveuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[games_archive.accounts.custom_validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='gamesarchiveuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[games_archive.accounts.custom_validators.validate_name]),
        ),
    ]
