# Generated by Django 5.1.1 on 2024-11-06 15:15

import games_archive.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_gamesarchiveuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesarchiveuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures/', validators=[games_archive.custom_validators.validate_file_size]),
        ),
    ]
